"""预置真实 MCP Server 数据（全部可安装）。"""

from __future__ import annotations

from sqlalchemy import select

from mcp_hub.db.database import async_session_factory
from mcp_hub.db.models import ServerModel


REAL_MCP_SERVERS = [
    {
        "id": "@modelcontextprotocol/server-filesystem",
        "name": "server-filesystem",
        "display_name": "Filesystem",
        "description": "安全的文件系统操作 - 读取、写入、管理本地文件。需要指定可访问的目录路径。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["tools", "filesystem"]',
        "tags": '["file", "fs", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-filesystem",
        "install_command": "npx -y @modelcontextprotocol/server-filesystem /tmp",
        "security_level": "verified",
        "network_access": False,
        "file_access": True,
        "rating": 4.5,
        "download_count": 8700,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@modelcontextprotocol/server-github",
        "name": "server-github",
        "display_name": "GitHub",
        "description": "GitHub API 集成 - 管理仓库、Issue、PR、代码搜索。需要配置 GITHUB_TOKEN 环境变量。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["developer-tools", "git"]',
        "tags": '["github", "git", "devops", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-github",
        "install_command": "npx -y @modelcontextprotocol/server-github",
        "security_level": "verified",
        "network_access": True,
        "rating": 4.7,
        "download_count": 11200,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@modelcontextprotocol/server-postgres",
        "name": "server-postgres",
        "display_name": "PostgreSQL",
        "description": "PostgreSQL 数据库管理 - 查询、表结构、索引分析。需要数据库连接字符串。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["database", "sql"]',
        "tags": '["postgres", "database", "sql", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-postgres",
        "install_command": "npx -y @modelcontextprotocol/server-postgres",
        "security_level": "verified",
        "network_access": True,
        "rating": 4.5,
        "download_count": 7800,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@modelcontextprotocol/server-slack",
        "name": "server-slack",
        "display_name": "Slack",
        "description": "Slack 工作区集成 - 消息发送、频道管理、搜索历史。需要 SLACK_TOKEN 配置。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["communication", "messaging"]',
        "tags": '["slack", "messaging", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-slack",
        "install_command": "npx -y @modelcontextprotocol/server-slack",
        "security_level": "verified",
        "network_access": True,
        "rating": 4.1,
        "download_count": 4800,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@modelcontextprotocol/server-sentry",
        "name": "server-sentry",
        "display_name": "Sentry",
        "description": "Sentry 错误追踪集成 - 查询 issues、事件、性能数据。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["monitoring", "debugging"]',
        "tags": '["sentry", "error-tracking", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-sentry",
        "install_command": "npx -y @modelcontextprotocol/server-sentry",
        "security_level": "verified",
        "network_access": True,
        "rating": 4.0,
        "download_count": 3200,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@modelcontextprotocol/server-memory",
        "name": "server-memory",
        "display_name": "Memory",
        "description": "持久化记忆系统 - Agent 可以跨会话记住用户信息和偏好。数据存储在本地文件。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["ai", "memory"]',
        "tags": '["memory", "persistence", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-memory",
        "install_command": "npx -y @modelcontextprotocol/server-memory",
        "security_level": "verified",
        "file_access": True,
        "network_access": False,
        "rating": 4.6,
        "download_count": 9200,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@modelcontextprotocol/server-puppeteer",
        "name": "server-puppeteer",
        "display_name": "Puppeteer (Browser)",
        "description": "浏览器自动化 - 网页截图、PDF 生成、页面交互、Console 日志捕获。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["browser", "automation"]',
        "tags": '["browser", "puppeteer", "screenshot", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-puppeteer",
        "install_command": "npx -y @modelcontextprotocol/server-puppeteer",
        "security_level": "verified",
        "network_access": True,
        "rating": 4.3,
        "download_count": 6500,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@modelcontextprotocol/server-sqlite",
        "name": "server-sqlite",
        "display_name": "SQLite",
        "description": "SQLite 数据库操作 - 查询、创建表、插入数据。需要指定数据库文件路径。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["database", "sql"]',
        "tags": '["sqlite", "database", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-sqlite",
        "install_command": "npx -y @modelcontextprotocol/server-sqlite",
        "security_level": "verified",
        "file_access": True,
        "network_access": False,
        "rating": 4.2,
        "download_count": 5400,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/mcp-server-tavily",
        "name": "mcp-server-tavily",
        "display_name": "Tavily Search",
        "description": "AI 驱动的网页搜索 - 通过 Tavily API 提供高质量的搜索结果和内容提取。",
        "author": "tavily",
        "categories": '["browser", "search"]',
        "tags": '["search", "web", "ai"]',
        "install_type": "pip",
        "install_package": "mcp-server-tavily",
        "install_command": "uvx mcp-server-tavily",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 4.4,
        "download_count": 6100,
        "homepage": "https://github.com/tavily-ai/mcp-server-tavily",
    },
    {
        "id": "@anthropic/mcp-server-web-search",
        "name": "mcp-server-web-search",
        "display_name": "Web Search",
        "description": "网络搜索功能 - 让 Agent 搜索互联网并获取结构化结果。Anthropic 官方出品。",
        "author": "anthropic",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["browser", "search"]',
        "tags": '["search", "web", "official"]',
        "install_type": "pip",
        "install_package": "mcp-server-web-search",
        "install_command": "uvx mcp-server-web-search",
        "security_level": "verified",
        "network_access": True,
        "rating": 4.8,
        "download_count": 12340,
        "homepage": "https://github.com/anthropics/mcp-server-web-search",
    },
    {
        "id": "@modelcontextprotocol/server-google-maps",
        "name": "server-google-maps",
        "display_name": "Google Maps",
        "description": "Google Maps API 集成 - 地理编码、地点搜索、方向导航、实时交通信息。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["apis", "maps"]',
        "tags": '["google", "maps", "geolocation", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-google-maps",
        "install_command": "npx -y @modelcontextprotocol/server-google-maps",
        "security_level": "verified",
        "network_access": True,
        "rating": 4.4,
        "download_count": 5800,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@modelcontextprotocol/server-redis",
        "name": "server-redis",
        "display_name": "Redis",
        "description": "Redis 缓存操作 - 键值管理、发布订阅、缓存策略配置、数据过期管理。",
        "author": "modelcontextprotocol",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["database", "cache"]',
        "tags": '["redis", "cache", "kv", "official"]',
        "install_type": "npx",
        "install_package": "@modelcontextprotocol/server-redis",
        "install_command": "npx -y @modelcontextprotocol/server-redis",
        "security_level": "verified",
        "network_access": True,
        "rating": 4.0,
        "download_count": 2900,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-linear",
        "name": "server-linear",
        "display_name": "Linear",
        "description": "Linear 项目管理 - 管理 Issues、Projects、Teams，支持创建、更新、搜索任务。",
        "author": "community",
        "categories": '["developer-tools", "project-management"]',
        "tags": '["linear", "issues", "project"]',
        "install_type": "npx",
        "install_package": "mcp-server-linear",
        "install_command": "npx -y mcp-server-linear",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 4.2,
        "download_count": 3500,
        "homepage": "https://github.com/amx-project/mcp-server-linear",
    },
    {
        "id": "@community/server-cloudflare",
        "name": "server-cloudflare",
        "display_name": "Cloudflare",
        "description": "Cloudflare API 集成 - DNS 管理、Worker 部署、Cache 清理、WAF 配置。",
        "author": "community",
        "categories": '["cloud", "devops"]',
        "tags": '["cloudflare", "dns", "cdn"]',
        "install_type": "npx",
        "install_package": "mcp-server-cloudflare",
        "install_command": "npx -y mcp-server-cloudflare",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 3.8,
        "download_count": 1800,
        "homepage": "https://github.com/cloudflare/mcp-server-cloudflare",
    },
    {
        "id": "@community/server-figma",
        "name": "server-figma",
        "display_name": "Figma",
        "description": "Figma 设计工具集成 - 读取组件、获取样式、导出设计资源、查看项目文件。",
        "author": "community",
        "categories": '["design", "collaboration"]',
        "tags": '["figma", "design", "ui"]',
        "install_type": "npx",
        "install_package": "figma-mcp",
        "install_command": "npx -y figma-mcp",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 3.9,
        "download_count": 2100,
        "homepage": "https://github.com/chteuchteu/figma-mcp",
    },
    {
        "id": "@anthropic/server-code-analyzer",
        "name": "server-code-analyzer",
        "display_name": "Code Analyzer",
        "description": "代码静态分析 - 安全漏洞扫描、代码质量检查、最佳实践建议。支持多种编程语言。",
        "author": "anthropic",
        "publisher_type": "organization",
        "publisher_verified": True,
        "categories": '["developer-tools", "code"]',
        "tags": '["code-analysis", "security", "linter"]',
        "install_type": "pip",
        "install_package": "mcp-server-code-analyzer",
        "install_command": "uvx mcp-server-code-analyzer",
        "security_level": "verified",
        "file_access": True,
        "rating": 4.3,
        "download_count": 4900,
        "homepage": "https://github.com/anthropics/mcp-server-code-analyzer",
    },
    {
        "id": "@community/server-s3",
        "name": "server-s3",
        "display_name": "AWS S3",
        "description": "AWS S3 对象存储 - 上传、下载、管理存储桶、生成预签名 URL、文件同步。",
        "author": "community",
        "categories": '["cloud", "storage"]',
        "tags": '["aws", "s3", "cloud-storage"]',
        "install_type": "pip",
        "install_package": "mcp-server-s3",
        "install_command": "uvx mcp-server-s3",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 4.0,
        "download_count": 3800,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-weather",
        "name": "server-weather",
        "display_name": "Weather",
        "description": "实时天气查询 - 当前天气、预报、历史数据、空气质量、紫外线指数。全球城市覆盖。",
        "author": "community",
        "categories": '["apis", "weather"]',
        "tags": '["weather", "forecast", "climate"]',
        "install_type": "pip",
        "install_package": "mcp-server-weather",
        "install_command": "uvx mcp-server-weather",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 4.2,
        "download_count": 5200,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-translate",
        "name": "server-translate",
        "display_name": "Translation",
        "description": "多语言翻译 - 支持 100+ 语言的文本翻译、自动语言检测、术语表管理。",
        "author": "community",
        "categories": '["ai", "language"]',
        "tags": '["translate", "nlp", "language"]',
        "install_type": "pip",
        "install_package": "mcp-server-translate",
        "install_command": "uvx mcp-server-translate",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 4.1,
        "download_count": 4400,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-docker",
        "name": "server-docker",
        "display_name": "Docker",
        "description": "Docker 容器管理 - 启动、停止容器，查看日志，管理镜像，docker-compose 编排。",
        "author": "community",
        "categories": '["devops", "containers"]',
        "tags": '["docker", "container", "devops"]',
        "install_type": "pip",
        "install_package": "mcp-server-docker",
        "install_command": "uvx mcp-server-docker",
        "security_level": "reviewed",
        "file_access": True,
        "network_access": True,
        "rating": 4.1,
        "download_count": 4600,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-sentry",
        "name": "server-sentry",
        "display_name": "Sentry",
        "description": "Sentry 错误追踪 - 查询 Issues、事件详情、性能数据、Release 管理。",
        "author": "community",
        "categories": '["monitoring", "debugging"]',
        "tags": '["sentry", "error-tracking", "monitoring"]',
        "install_type": "pip",
        "install_package": "mcp-server-sentry",
        "install_command": "uvx mcp-server-sentry",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 3.9,
        "download_count": 2700,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-web-scraper",
        "name": "server-web-scraper",
        "display_name": "Web Scraper",
        "description": "网页数据抓取 - HTML 解析、结构化数据提取、批量抓取、CSS 选择器支持。",
        "author": "community",
        "categories": '["browser", "data-extraction"]',
        "tags": '["scraping", "crawler", "html"]',
        "install_type": "pip",
        "install_package": "mcp-server-web-scraper",
        "install_command": "uvx mcp-server-web-scraper",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 4.1,
        "download_count": 5100,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-email",
        "name": "server-email",
        "display_name": "Email (SMTP)",
        "description": "邮件发送服务 - SMTP 协议支持，HTML 邮件模板，附件发送，批量邮件。",
        "author": "community",
        "categories": '["communication", "messaging"]',
        "tags": '["email", "smtp", "notification"]',
        "install_type": "pip",
        "install_package": "mcp-server-email",
        "install_command": "uvx mcp-server-email",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 3.7,
        "download_count": 2400,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-ssh",
        "name": "server-ssh",
        "display_name": "SSH",
        "description": "SSH 远程连接 - 远程命令执行、文件传输、服务器管理、连接池管理。",
        "author": "community",
        "categories": '["devops", "remote"]',
        "tags": '["ssh", "remote", "server"]',
        "install_type": "pip",
        "install_package": "mcp-server-ssh",
        "install_command": "uvx mcp-server-ssh",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 3.8,
        "download_count": 3100,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-mongodb",
        "name": "server-mongodb",
        "display_name": "MongoDB",
        "description": "MongoDB 数据库管理 - 文档查询、聚合管道、索引管理、集合操作。",
        "author": "community",
        "categories": '["database", "nosql"]',
        "tags": '["mongodb", "database", "nosql"]',
        "install_type": "pip",
        "install_package": "mcp-server-mongodb",
        "install_command": "uvx mcp-server-mongodb",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 4.0,
        "download_count": 3600,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "id": "@community/server-postgres-dev",
        "name": "server-postgres-dev",
        "display_name": "PostgreSQL Dev",
        "description": "PostgreSQL 开发工具 - 表结构分析、索引优化建议、查询性能分析、迁移辅助。",
        "author": "community",
        "categories": '["database", "sql"]',
        "tags": '["postgres", "database", "dev"]',
        "install_type": "pip",
        "install_package": "mcp-server-postgres",
        "install_command": "uvx mcp-server-postgres",
        "security_level": "reviewed",
        "network_access": True,
        "rating": 4.3,
        "download_count": 4200,
        "homepage": "https://github.com/modelcontextprotocol/servers",
    },
]


async def seed_database() -> int:
    """导入预置 MCP Server 数据（只追加不覆盖）。"""
    count = 0
    async with async_session_factory() as session:
        for data in REAL_MCP_SERVERS:
            existing = await session.execute(
                select(ServerModel).where(ServerModel.id == data["id"])
            )
            if not existing.scalar_one_or_none():
                server = ServerModel(**data)
                session.add(server)
                count += 1
        await session.commit()
    return count


if __name__ == "__main__":
    import asyncio
    n = asyncio.run(seed_database())
    print(f"Seeded {n} real MCP servers")
