"""预置 MCP Server 种子数据 — 高质量社区 Server。"""

from __future__ import annotations

from sqlalchemy import select

from mcp_hub.db.database import async_session_factory
from mcp_hub.db.models import ServerModel

REAL_MCP_SERVERS = [
    {"id": "@modelcontextprotocol/server-filesystem", "name": "server-filesystem", "display_name": "Filesystem", "author": "modelcontextprotocol", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"tools\", \"filesystem\"]", "tags": "[\"file\", \"fs\", \"official\"]", "install_type": "npx", "install_package": "@modelcontextprotocol/server-filesystem", "install_command": "npx -y @modelcontextprotocol/server-filesystem /tmp", "security_level": "verified", "network_access": False, "file_access": True, "rating": 4.5, "download_count": 21100, "homepage": "https://github.com/modelcontextprotocol/servers", "license": "MIT", "description": "安全的文件系统操作工具，支持读写和管理本地文件。"},  # noqa: E501
    {"id": "@modelcontextprotocol/server-github", "name": "server-github", "display_name": "GitHub", "author": "modelcontextprotocol", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"developer-tools\", \"git\"]", "tags": "[\"github\", \"git\", \"devops\", \"official\"]", "install_type": "npx", "install_package": "@modelcontextprotocol/server-github", "install_command": "npx -y @modelcontextprotocol/server-github", "security_level": "verified", "network_access": True, "rating": 4.7, "download_count": 27800, "homepage": "https://github.com/modelcontextprotocol/servers", "license": "MIT", "description": "GitHub API 集成工具，支持仓库管理、Issue 追踪和代码搜索。"},  # noqa: E501
    {"id": "@modelcontextprotocol/server-postgres", "name": "server-postgres", "display_name": "PostgreSQL", "author": "modelcontextprotocol", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"database\", \"developer-tools\"]", "tags": "[\"sql\", \"database\", \"postgres\", \"official\"]", "install_type": "npx", "install_package": "@modelcontextprotocol/server-postgres", "install_command": "npx -y @modelcontextprotocol/server-postgres", "security_level": "verified", "network_access": True, "rating": 4.6, "download_count": 18900, "homepage": "https://github.com/modelcontextprotocol/servers", "license": "MIT", "description": "PostgreSQL 数据库管理工具，支持 SQL 查询、表结构和数据导出。"},  # noqa: E501
    {"id": "@modelcontextprotocol/server-puppeteer", "name": "server-puppeteer", "display_name": "Puppeteer", "author": "modelcontextprotocol", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"browser\"]", "tags": "[\"browser\", \"web\", \"scraping\", \"official\"]", "install_type": "npx", "install_package": "@modelcontextprotocol/server-puppeteer", "install_command": "npx -y @modelcontextprotocol/server-puppeteer", "security_level": "verified", "network_access": True, "rating": 4.8, "download_count": 34200, "homepage": "https://github.com/modelcontextprotocol/servers", "license": "MIT", "description": "浏览器自动化工具，支持网页截图、内容抓取和交互操作。"},  # noqa: E501
    {"id": "@modelcontextprotocol/server-slack", "name": "server-slack", "display_name": "Slack", "author": "modelcontextprotocol", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"communication\"]", "tags": "[\"slack\", \"messaging\", \"official\"]", "install_type": "npx", "install_package": "@modelcontextprotocol/server-slack", "install_command": "npx -y @modelcontextprotocol/server-slack", "security_level": "verified", "network_access": True, "rating": 4.4, "download_count": 15300, "homepage": "https://github.com/modelcontextprotocol/servers", "license": "MIT", "description": "Slack 集成工具，支持消息收发、频道管理和搜索。"},  # noqa: E501
    {"id": "@anthropic/web-search", "name": "web-search", "display_name": "Web Search", "author": "anthropic", "publisher_type": "official", "publisher_verified": True, "categories": "[\"browser\"]", "tags": "[\"search\", \"web\"]", "install_type": "npx", "install_package": "@anthropic/web-search", "install_command": "npx -y @anthropic/web-search", "security_level": "verified", "network_access": True, "rating": 4.8, "download_count": 45100, "homepage": "https://github.com/anthropics/anthropic-quickstarts", "license": "MIT", "description": "网页搜索工具，支持实时搜索并返回结构化结果。"},  # noqa: E501
    {"id": "@anthropic/computer-use", "name": "computer-use", "display_name": "Computer Use", "author": "anthropic", "publisher_type": "official", "publisher_verified": True, "categories": "[\"developer-tools\"]", "tags": "[\"computer\", \"automation\", \"official\"]", "install_type": "pip", "install_package": "anthropic-computer-use", "install_command": "pip install anthropic-computer-use", "security_level": "verified", "network_access": False, "file_access": True, "rating": 4.9, "download_count": 56700, "homepage": "https://github.com/anthropics/anthropic-quickstarts", "license": "MIT", "description": "计算机操作自动化工具，支持模拟操作和文件管理。"},  # noqa: E501
    {"id": "@openai/web-search", "name": "web-search", "display_name": "Web Search (OpenAI)", "author": "openai", "publisher_type": "official", "publisher_verified": True, "categories": "[\"browser\"]", "tags": "[\"search\", \"web\"]", "install_type": "npx", "install_package": "@openai/web-search", "install_command": "npx -y @openai/web-search", "security_level": "verified", "network_access": True, "rating": 4.6, "download_count": 38900, "homepage": "https://github.com/openai/openai-mcp", "license": "MIT", "description": "OpenAI 提供的网络搜索工具，支持实时信息检索。"},  # noqa: E501
    {"id": "@cloudflare/mcp-server-cloudflare", "name": "mcp-server-cloudflare", "display_name": "Cloudflare", "author": "cloudflare", "publisher_type": "official", "publisher_verified": True, "categories": "[\"cloud\", \"developer-tools\"]", "tags": "[\"cloudflare\", \"cdn\", \"workers\"]", "install_type": "npx", "install_package": "@cloudflare/mcp-server-cloudflare", "install_command": "npx -y @cloudflare/mcp-server-cloudflare", "security_level": "verified", "network_access": True, "rating": 4.5, "download_count": 22400, "homepage": "https://github.com/cloudflare/mcp-server-cloudflare", "license": "MIT", "description": "Cloudflare 管理工具，支持 Workers、KV 和 CDN 配置。"},  # noqa: E501
    {"id": "@github/github-mcp-server", "name": "github-mcp-server", "display_name": "GitHub MCP", "author": "github", "publisher_type": "official", "publisher_verified": True, "categories": "[\"developer-tools\", \"git\"]", "tags": "[\"github\", \"git\", \"devops\"]", "install_type": "npx", "install_package": "@github/github-mcp-server", "install_command": "npx -y @github/github-mcp-server", "security_level": "verified", "network_access": True, "rating": 4.9, "download_count": 62300, "homepage": "https://github.com/github/github-mcp-server", "license": "MIT", "description": "GitHub 官方 MCP 服务器，支持仓库管理和代码审查。"},  # noqa: E501
    {"id": "@clickhouse/mcp-server-clickhouse", "name": "mcp-server-clickhouse", "display_name": "ClickHouse", "author": "clickhouse", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"database\"]", "tags": "[\"sql\", \"analytics\", \"clickhouse\"]", "install_type": "pip", "install_package": "mcp-server-clickhouse", "install_command": "pip install mcp-server-clickhouse", "security_level": "verified", "network_access": True, "rating": 4.3, "download_count": 8900, "homepage": "https://github.com/ClickHouse/mcp-server-clickhouse", "license": "MIT", "description": "ClickHouse 分析数据库管理工具，支持 SQL 查询和表管理。"},  # noqa: E501
    {"id": "@docker/mcp-server-docker", "name": "mcp-server-docker", "display_name": "Docker", "author": "docker", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"developer-tools\", \"devops\"]", "tags": "[\"docker\", \"container\", \"devops\"]", "install_type": "npx", "install_package": "@docker/mcp-server-docker", "install_command": "npx -y @docker/mcp-server-docker", "security_level": "verified", "network_access": True, "file_access": True, "rating": 4.5, "download_count": 19800, "homepage": "https://github.com/docker/mcp-server-docker", "license": "MIT", "description": "Docker 容器管理工具，支持镜像构建和容器编排。"},  # noqa: E501
    {"id": "@huggingface/mcp-server-huggingface", "name": "mcp-server-huggingface", "display_name": "HuggingFace", "author": "huggingface", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"ai\"]", "tags": "[\"ai\", \"ml\", \"huggingface\"]", "install_type": "pip", "install_package": "mcp-server-huggingface", "install_command": "pip install mcp-server-huggingface", "security_level": "verified", "network_access": True, "rating": 4.4, "download_count": 15600, "homepage": "https://github.com/huggingface/mcp-server-huggingface", "license": "Apache-2.0", "description": "HuggingFace 模型库工具，支持模型搜索和推理调用。"},  # noqa: E501
    {"id": "@datadog/mcp-server-datadog", "name": "mcp-server-datadog", "display_name": "Datadog", "author": "datadog", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"monitoring\"]", "tags": "[\"monitoring\", \"datadog\"]", "install_type": "pip", "install_package": "mcp-server-datadog", "install_command": "pip install mcp-server-datadog", "security_level": "verified", "network_access": True, "rating": 4.2, "download_count": 12300, "homepage": "https://github.com/DataDog/mcp-server-datadog", "license": "MIT", "description": "Datadog 监控工具，支持查看仪表盘和管理告警。"},  # noqa: E501
    {"id": "@kubernetes/mcp-server-kubernetes", "name": "mcp-server-kubernetes", "display_name": "Kubernetes", "author": "kubernetes", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"devops\", \"cloud\"]", "tags": "[\"k8s\", \"kubernetes\", \"devops\"]", "install_type": "pip", "install_package": "mcp-server-kubernetes", "install_command": "pip install mcp-server-kubernetes", "security_level": "verified", "network_access": True, "rating": 4.3, "download_count": 14100, "homepage": "https://github.com/kubernetes-sigs/mcp-server-kubernetes", "license": "Apache-2.0", "description": "Kubernetes 集群管理工具，支持 Pod 管理和日志查看。"},  # noqa: E501
    {"id": "@sentry/mcp-server-sentry", "name": "mcp-server-sentry", "display_name": "Sentry", "author": "sentry", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"monitoring\"]", "tags": "[\"sentry\", \"error-tracking\"]", "install_type": "pip", "install_package": "mcp-server-sentry", "install_command": "pip install mcp-server-sentry", "security_level": "verified", "network_access": True, "rating": 4.1, "download_count": 9800, "homepage": "https://github.com/getsentry/mcp-server-sentry", "license": "MIT", "description": "Sentry 错误追踪工具，支持异常查看和性能监控。"},  # noqa: E501
    {"id": "@google/mcp-server-google-maps", "name": "mcp-server-google-maps", "display_name": "Google Maps", "author": "google", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"maps\"]", "tags": "[\"maps\", \"location\"]", "install_type": "npx", "install_package": "@google/mcp-server-google-maps", "install_command": "npx -y @google/mcp-server-google-maps", "security_level": "verified", "network_access": True, "rating": 4.3, "download_count": 11200, "homepage": "https://github.com/google/mcp-server-google-maps", "license": "Apache-2.0", "description": "Google 地图工具，支持地点搜索和路线规划。"},  # noqa: E501
    {"id": "@notion/mcp-server-notion", "name": "mcp-server-notion", "display_name": "Notion", "author": "notion", "publisher_type": "organization", "publisher_verified": True, "categories": "[\"productivity\"]", "tags": "[\"notion\", \"notes\"]", "install_type": "npx", "install_package": "@notion/mcp-server-notion", "install_command": "npx -y @notion/mcp-server-notion", "security_level": "verified", "network_access": True, "rating": 4.2, "download_count": 13400, "homepage": "https://github.com/notionhq/mcp-server-notion", "license": "MIT", "description": "Notion 知识库工具，支持页面管理和数据库查询。"},  # noqa: E501
]


async def seed_database():
    async with async_session_factory() as session:
        total = 0
        skipped = 0
        for data in REAL_MCP_SERVERS:
            existing = await session.execute(
                select(ServerModel).where(ServerModel.id == data["id"])
            )
            if existing.scalar_one_or_none():
                skipped += 1
                continue
            session.add(ServerModel(**data))
            total += 1
        await session.commit()
        # print(f"  Seed: {total} new, {skipped} skipped")  # noqa: T201
